INPUT:
  SIZE: (16000,)  # 1 second of audio at 16kHz
  TRANSFORMS: ['audio_normalize', 'audio_augment']

DATASET:
  NAME: 'UASpeechDataset'
  ROOT: '/home/zsim710/XDED/speechbrain/datasets/UASpeech'

MODEL:
  BACKBONE:
    NAME: 'audio_cnn'
    PRETRAINED: False
  HEAD:
    NAME: 'ClassificationHead'

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
    SAMPLER: 'RandomDomainSampler'
  TEST:
    BATCH_SIZE: 32
    SAMPLER: 'SequentialSampler'
  NUM_WORKERS: 4